"""Cell definitions for Week 4 Day 2 forecasting notebook."""


def get_day2_cells(md, code, common_helper):
    """Return notebook cells for Day 2."""
    return [
        md(
            "# Week 4 Day 2 – Time Series Forecasting\n\n"
            "## Learning objectives\n"
            "- Understand trend, seasonality, and noise\n"
            "- Decompose a time series and test stationarity\n"
            "- Use chronological train/test splits\n"
            "- Build baseline, statistical, Prophet, ML, and deep learning forecasts\n"
            "- Compare models with MAE, RMSE, and MAPE"
        ),
        md(
            "## Section 1 — Introduction to Time Series\n\n"
            "In time series data, **order matters**. Past values can influence future values (**autocorrelation**).\n\n"
            "- **Trend:** long-term increase or decrease\n"
            "- **Seasonality:** repeating pattern (for example monthly)\n"
            "- **Noise / residual:** random variation\n\n"
            "> **Never use random train/test split** for forecasting. Future data must not leak into training."
        ),
        code(
            "import warnings\n"
            "warnings.filterwarnings('ignore')\n\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n\n"
            "from statsmodels.tsa.seasonal import seasonal_decompose\n"
            "from statsmodels.tsa.stattools import adfuller\n"
            "from statsmodels.tsa.arima.model import ARIMA\n"
            "from statsmodels.tsa.statespace.sarimax import SARIMAX\n"
            "from statsmodels.tsa.ar_model import AutoReg\n\n"
            "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, HistGradientBoostingRegressor\n"
            "from sklearn.metrics import mean_absolute_error, mean_squared_error\n\n"
            "%matplotlib inline\n"
            "sns.set_theme(style='whitegrid')\n"
            "RANDOM_STATE = 42\n"
            "RUN_DEEP_LEARNING = True  # set False on slow machines\n"
            "TEST_RATIO = 0.2\n"
            "SEASONAL_PERIOD = 12\n\n"
            "try:\n"
            "    from xgboost import XGBRegressor\n"
            "except ImportError:\n"
            "    XGBRegressor = None\n"
            "    print('xgboost not installed — using HistGradientBoostingRegressor as fallback.')\n\n"
            "try:\n"
            "    from prophet import Prophet\n"
            "except ImportError:\n"
            "    Prophet = None\n"
            "    print('prophet not installed — optional section will be skipped. Install with: pip install prophet')\n\n"
            "try:\n"
            "    import torch\n"
            "    import torch.nn as nn\n"
            "    from torch.utils.data import DataLoader, TensorDataset\n"
            "    TORCH_AVAILABLE = True\n"
            "except ImportError:\n"
            "    TORCH_AVAILABLE = False\n"
            "    print('PyTorch not installed — deep learning section will be skipped.')"
        ),
        md("### Shared path helper"),
        code(common_helper),
        md(
            "## Section 2 — Load and Visualize Time Series\n\n"
            "We use the classic **AirPassengers** series (embedded locally so the notebook runs offline)."
        ),
        code(
            "AIRPASSENGERS_VALUES = [\n"
            "    112,118,132,129,121,135,148,148,136,119,104,118,115,126,141,135,125,149,170,164,151,180,193,186,\n"
            "    174,160,196,218,211,186,231,257,263,249,280,284,277,317,325,335,318,362,348,363,435,491,505,404,\n"
            "    359,437,506,432,405,481,517,525,595,596,628,622,598,548,582,611,604,634,658,622,644,653,681,655,\n"
            "    622,727,725,706,734,750,711,747,785,715,773,828,726,796,867,912,820,853,895,890,810,812,888,913,\n"
            "    929,1045,1089,1005,1066,1072,1102,1028,1083,1114,1074,1084,1152,1178,1159,1163,1185,1154\n"
            "]\n\n"
            "def load_air_passengers():\n"
            "    if AIRPASSENGERS_CSV.exists():\n"
            "        df = pd.read_csv(AIRPASSENGERS_CSV, parse_dates=['date'])\n"
            "    else:\n"
            "        dates = pd.date_range('1949-01', periods=len(AIRPASSENGERS_VALUES), freq='MS')\n"
            "        df = pd.DataFrame({'date': dates, 'passengers': AIRPASSENGERS_VALUES})\n"
            "        df.to_csv(AIRPASSENGERS_CSV, index=False)\n"
            "        print('Saved:', AIRPASSENGERS_CSV)\n"
            "    df = df.sort_values('date').set_index('date')\n"
            "    return df\n\n"
            "ts = load_air_passengers()\n"
            "y = ts['passengers'].astype(float)\n"
            "display(ts.head())\n"
            "print('Length:', len(y))"
        ),
        code(
            "plt.figure(figsize=(11, 4))\n"
            "plt.plot(y.index, y.values, color='steelblue')\n"
            "plt.title('AirPassengers — monthly totals')\n"
            "plt.xlabel('Date'); plt.ylabel('Passengers')\n"
            "plt.tight_layout()\n"
            "plt.savefig(FIGURES_DIR / 'day2_time_series.png', dpi=120, bbox_inches='tight')\n"
            "plt.show()"
        ),
        md(
            "## Section 3 — Time-Series Decomposition\n\n"
            "Observed ≈ trend + seasonality + residual. Decomposition helps choose models (trend → differencing, seasonality → SARIMA/seasonal naive)."
        ),
        code(
            "decomp = seasonal_decompose(y, model='additive', period=SEASONAL_PERIOD)\n"
            "fig = decomp.plot()\n"
            "fig.set_size_inches(10, 8)\n"
            "plt.tight_layout()\n"
            "plt.savefig(FIGURES_DIR / 'day2_decomposition.png', dpi=120, bbox_inches='tight')\n"
            "plt.show()"
        ),
        md(
            "## Section 4 — Stationarity\n\n"
            "A stationary series has relatively stable mean and variance (no strong trend or shifting seasonality). "
            "Many classical models assume stationarity or use differencing.\n\n"
            "**Differencing** models changes instead of raw levels."
        ),
        code(
            "roll_mean = y.rolling(12).mean()\n"
            "roll_std = y.rolling(12).std()\n"
            "fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)\n"
            "axes[0].plot(y, label='Original'); axes[0].legend()\n"
            "axes[0].plot(roll_mean, color='red', label='12-month rolling mean'); axes[0].legend()\n"
            "axes[1].plot(roll_std, color='darkorange'); axes[1].set_title('Rolling std')\n"
            "diff1 = y.diff().dropna()\n"
            "axes[2].plot(diff1, color='green'); axes[2].set_title('First difference')\n"
            "plt.tight_layout(); plt.show()\n\n"
            "adf = adfuller(y.dropna())\n"
            "print(f'ADF statistic: {adf[0]:.3f}, p-value: {adf[1]:.4f}')\n"
            "print('If p-value > 0.05, series is likely non-stationary (reject null with caution).')"
        ),
        code(
            "seasonal_diff = y.diff(SEASONAL_PERIOD).dropna()\n"
            "plt.figure(figsize=(10, 3))\n"
            "plt.plot(seasonal_diff, color='purple')\n"
            "plt.title(f'Seasonal difference (lag={SEASONAL_PERIOD})')\n"
            "plt.tight_layout(); plt.show()"
        ),
        md("## Section 5 — Time-Based Train/Test Split"),
        code(
            "split_idx = int(len(y) * (1 - TEST_RATIO))\n"
            "train, test = y.iloc[:split_idx], y.iloc[split_idx:]\n"
            "split_date = test.index[0]\n"
            "print('Train:', train.index.min().date(), 'to', train.index.max().date(), '| n =', len(train))\n"
            "print('Test :', test.index.min().date(), 'to', test.index.max().date(), '| n =', len(test))\n\n"
            "plt.figure(figsize=(11, 4))\n"
            "plt.plot(train, label='Train', color='steelblue')\n"
            "plt.plot(test, label='Test', color='darkorange')\n"
            "plt.axvline(split_date, color='red', linestyle='--', label='Split')\n"
            "plt.legend(); plt.title('Chronological train/test split')\n"
            "plt.tight_layout(); plt.show()"
        ),
        md(
            "### Data leakage warning\n"
            "Do not shuffle time series rows. Do not scale or impute using statistics from the full dataset including the test period."
        ),
        md(
            "## Section 6 — Baseline Forecasts\n\n"
            "Baselines are simple rules. **Complex models are useful only if they beat simple baselines.**"
        ),
        code(
            "def evaluate_forecast(name, y_true, y_pred, store, extra=None):\n"
            "  y_true = np.asarray(y_true, dtype=float)\n"
            "  y_pred = np.asarray(y_pred, dtype=float)\n"
            "  mae = mean_absolute_error(y_true, y_pred)\n"
            "  rmse = np.sqrt(mean_squared_error(y_true, y_pred))\n"
            "  mape = np.mean(np.abs((y_true - y_pred) / np.clip(y_true, 1e-6, None))) * 100\n"
            "  row = {'Model': name, 'MAE': mae, 'RMSE': rmse, 'MAPE': mape}\n"
            "  if extra:\n"
            "      row.update(extra)\n"
            "  store.append(row)\n"
            "  return row\n\n"
            "results = []\n\n"
            "# 1) Naive: last observed value\n"
            "naive_pred = np.repeat(train.iloc[-1], len(test))\n"
            "evaluate_forecast('Naive', test, naive_pred, results)\n\n"
            "# 2) Seasonal naive: value from same month last year\n"
            "seasonal_preds = []\n"
            "for dt in test.index:\n"
            "    lag_date = dt - pd.DateOffset(years=1)\n"
            "    val = y.loc[lag_date] if lag_date in y.index else train.iloc[-1]\n"
            "    seasonal_preds.append(val)\n"
            "evaluate_forecast('Seasonal Naive', test, seasonal_preds, results)\n\n"
            "# 3) Moving average of last 12 train points\n"
            "ma_window = 12\n"
            "ma_value = train.iloc[-ma_window:].mean()\n"
            "ma_pred = np.repeat(ma_value, len(test))\n"
            "evaluate_forecast('Moving Average (12)', test, ma_pred, results)\n\n"
            "baseline_df = pd.DataFrame(results).round(3)\n"
            "display(baseline_df)"
        ),
        code(
            "plt.figure(figsize=(11, 4))\n"
            "plt.plot(test.index, test.values, label='Actual', linewidth=2)\n"
            "plt.plot(test.index, seasonal_preds, label='Seasonal Naive', linestyle='--')\n"
            "plt.title('Actual vs Seasonal Naive forecast')\n"
            "plt.legend(); plt.tight_layout(); plt.show()"
        ),
        md("## Section 7 — Classical Statistical Models"),
        code(
            "def forecast_statistical(name, fitted, steps):\n"
            "    pred = fitted.forecast(steps=steps)\n"
            "    return np.asarray(pred)\n\n"
            "stat_models = {}"
        ),
        code(
            "# AR(p,0,0) via AutoReg\n"
            "ar_order = 2\n"
            "ar_model = AutoReg(train, lags=ar_order, old_names=False).fit()\n"
            "ar_pred = forecast_statistical('AR', ar_model, len(test))\n"
            "evaluate_forecast(f'AR({ar_order})', test, ar_pred, results)\n"
            "stat_models['AR'] = ar_model"
        ),
        code(
            "# MA(0,0,q)\n"
            "ma_order = 1\n"
            "ma_model = ARIMA(train, order=(0, 0, ma_order)).fit()\n"
            "ma_pred = forecast_statistical('MA', ma_model, len(test))\n"
            "evaluate_forecast(f'MA({ma_order})', test, ma_pred, results)"
        ),
        code(
            "# ARMA(p,0,q)\n"
            "p, q = 2, 1\n"
            "arma_model = ARIMA(train, order=(p, 0, q)).fit()\n"
            "arma_pred = forecast_statistical('ARMA', arma_model, len(test))\n"
            "evaluate_forecast(f'ARMA({p},{q})', test, arma_pred, results)"
        ),
        code(
            "# ARIMA(p,d,q)\n"
            "p, d, q = 1, 1, 1\n"
            "arima_model = ARIMA(train, order=(p, d, q)).fit()\n"
            "arima_pred = forecast_statistical('ARIMA', arima_model, len(test))\n"
            "evaluate_forecast(f'ARIMA({p},{d},{q})', test, arima_pred, results)\n\n"
            "plt.figure(figsize=(11, 4))\n"
            "plt.plot(test.index, test.values, label='Actual')\n"
            "plt.plot(test.index, arima_pred, label='ARIMA forecast', linestyle='--')\n"
            "plt.legend(); plt.title('ARIMA on test period'); plt.tight_layout(); plt.show()"
        ),
        code(
            "# SARIMA\n"
            "order = (1, 1, 1)\n"
            "seasonal_order = (1, 1, 1, SEASONAL_PERIOD)\n"
            "sarima_model = SARIMAX(train, order=order, seasonal_order=seasonal_order,\n"
            "                       enforce_stationarity=False, enforce_invertibility=False).fit(disp=False)\n"
            "sarima_pred = sarima_model.forecast(len(test))\n"
            "evaluate_forecast(f'SARIMA{order}x{seasonal_order}', test, sarima_pred, results)\n\n"
            "plt.figure(figsize=(11, 4))\n"
            "plt.plot(test.index, test.values, label='Actual')\n"
            "plt.plot(test.index, sarima_pred, label='SARIMA', linestyle='--')\n"
            "plt.legend(); plt.tight_layout(); plt.show()"
        ),
        md(
            "## Section 8 — Prophet (optional)\n\n"
            "Prophet is useful for business series with trend, seasonality, holidays, missing values, and outliers.\n\n"
            "Install (optional): `pip install prophet`"
        ),
        code(
            "if Prophet is not None:\n"
            "    prophet_train = train.reset_index().rename(columns={'date': 'ds', 'passengers': 'y'})\n"
            "    m_prophet = Prophet(yearly_seasonality=True, weekly_seasonality=False, daily_seasonality=False)\n"
            "    m_prophet.fit(prophet_train)\n"
            "    future = pd.DataFrame({'ds': test.index})\n"
            "    fcst = m_prophet.predict(future)\n"
            "    prophet_pred = fcst['yhat'].values\n"
            "    evaluate_forecast('Prophet', test, prophet_pred, results)\n"
            "    fig = m_prophet.plot(fcst)\n"
            "    plt.tight_layout(); plt.show()\n"
            "else:\n"
            "    print('Skipping Prophet — package not available.')"
        ),
        md(
            "## Section 9 — Machine Learning Forecasting with Feature Engineering\n\n"
            "Tree models do not see time order automatically. We create **lags**, **rolling** stats, and **calendar** features."
        ),
        code(
            "def make_supervised_frame(series, max_lag=12):\n"
            "    df = pd.DataFrame({'y': series})\n"
            "    for lag in [1, 2, max_lag]:\n"
            "        df[f'lag_{lag}'] = df['y'].shift(lag)\n"
            "    df['roll_mean_3'] = df['y'].shift(1).rolling(3).mean()\n"
            "    df['roll_std_3'] = df['y'].shift(1).rolling(3).std()\n"
            "    df['month'] = df.index.month\n"
            "    df['quarter'] = df.index.quarter\n"
            "    df['year'] = df.index.year\n"
            "    df['time_idx'] = np.arange(len(df))\n"
            "    return df.dropna()\n\n"
            "full_feat = make_supervised_frame(y, max_lag=12)\n"
            "train_feat = full_feat.loc[full_feat.index <= train.index.max()]\n"
            "test_feat = full_feat.loc[full_feat.index.isin(test.index)]\n"
            "feature_cols = [c for c in full_feat.columns if c != 'y']\n"
            "X_tr, y_tr = train_feat[feature_cols], train_feat['y']\n"
            "X_te, y_te = test_feat[feature_cols], test_feat['y']\n\n"
            "rf = RandomForestRegressor(n_estimators=200, random_state=RANDOM_STATE)\n"
            "rf.fit(X_tr, y_tr)\n"
            "rf_pred = rf.predict(X_te)\n"
            "evaluate_forecast('Random Forest', y_te, rf_pred, results)\n\n"
            "if XGBRegressor is not None:\n"
            "    xgb = XGBRegressor(n_estimators=300, learning_rate=0.05, max_depth=4, random_state=RANDOM_STATE, verbosity=0)\n"
            "    xgb.fit(X_tr, y_tr)\n"
            "    xgb_pred = xgb.predict(X_te)\n"
            "    evaluate_forecast('XGBoost', y_te, xgb_pred, results)\n"
            "else:\n"
            "    hgb = HistGradientBoostingRegressor(random_state=RANDOM_STATE)\n"
            "    hgb.fit(X_tr, y_tr)\n"
            "    hgb_pred = hgb.predict(X_te)\n"
            "    evaluate_forecast('HistGradientBoosting (XGB fallback)', y_te, hgb_pred, results)\n\n"
            "plt.figure(figsize=(11, 4))\n"
            "plt.plot(y_te.index, y_te.values, label='Actual')\n"
            "plt.plot(y_te.index, rf_pred, label='Random Forest', linestyle='--')\n"
            "plt.legend(); plt.title('ML forecast (feature-based)'); plt.tight_layout(); plt.show()"
        ),
        md(
            "## Section 10 — Deep Learning Forecasting (optional)\n\n"
            "- **LSTM:** captures longer dependencies; needs more data and compute\n"
            "- **GRU:** simpler, often a good compromise\n"
            "- **Transformer:** attention over past steps; powerful but data-hungry\n\n"
            "Set `RUN_DEEP_LEARNING = False` if training is too slow."
        ),
        code(
            "dl_predictions = {}\n\n"
            "if RUN_DEEP_LEARNING and TORCH_AVAILABLE:\n"
            "    from sklearn.preprocessing import MinMaxScaler\n\n"
            "    def make_sequences(values, seq_len):\n"
            "        X, y_seq = [], []\n"
            "        for i in range(seq_len, len(values)):\n"
            "            X.append(values[i-seq_len:i])\n"
            "            y_seq.append(values[i])\n"
            "        return np.array(X), np.array(y_seq)\n\n"
            "    seq_len = 12\n"
            "    scaler_dl = MinMaxScaler()\n"
            "    scaled = scaler_dl.fit_transform(y.values.reshape(-1, 1)).ravel()\n"
            "    X_all, y_all = make_sequences(scaled, seq_len)\n"
            "    dates_all = y.index[seq_len:]\n"
            "    train_mask = dates_all <= train.index.max()\n"
            "    X_dl_train, y_dl_train = X_all[train_mask], y_all[train_mask]\n"
            "    X_dl_test, y_dl_test = X_all[~train_mask], y_all[~train_mask]\n"
            "    test_dates_dl = dates_all[~train_mask]\n\n"
            "    class LSTMReg(nn.Module):\n"
            "        def __init__(self, hidden=32):\n"
            "            super().__init__()\n"
            "            self.rnn = nn.LSTM(1, hidden, batch_first=True)\n"
            "            self.fc = nn.Linear(hidden, 1)\n"
            "        def forward(self, x):\n"
            "            out, _ = self.rnn(x)\n"
            "            return self.fc(out[:, -1, :]).squeeze(-1)\n\n"
            "    class GRUReg(nn.Module):\n"
            "        def __init__(self, hidden=32):\n"
            "            super().__init__()\n"
            "            self.rnn = nn.GRU(1, hidden, batch_first=True)\n"
            "            self.fc = nn.Linear(hidden, 1)\n"
            "        def forward(self, x):\n"
            "            out, _ = self.rnn(x)\n"
            "            return self.fc(out[:, -1, :]).squeeze(-1)\n\n"
            "    class SimpleTransformerReg(nn.Module):\n"
            "        def __init__(self, seq_len, d_model=16):\n"
            "            super().__init__()\n"
            "            self.input_proj = nn.Linear(1, d_model)\n"
            "            layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=2, batch_first=True, dim_feedforward=32)\n"
            "            self.encoder = nn.TransformerEncoder(layer, num_layers=1)\n"
            "            self.fc = nn.Linear(d_model, 1)\n"
            "        def forward(self, x):\n"
            "            h = self.input_proj(x)\n"
            "            h = self.encoder(h)\n"
            "            return self.fc(h[:, -1, :]).squeeze(-1)\n\n"
            "    def train_torch_model(model_cls, label, epochs=15, **kwargs):\n"
            "        torch.manual_seed(RANDOM_STATE)\n"
            "        model = model_cls(**kwargs)\n"
            "        opt = torch.optim.Adam(model.parameters(), lr=0.01)\n"
            "        loss_fn = nn.MSELoss()\n"
            "        X_t = torch.tensor(X_dl_train, dtype=torch.float32).unsqueeze(-1)\n"
            "        y_t = torch.tensor(y_dl_train, dtype=torch.float32)\n"
            "        loader = DataLoader(TensorDataset(X_t, y_t), batch_size=16, shuffle=True)\n"
            "        model.train()\n"
            "        for _ in range(epochs):\n"
            "            for xb, yb in loader:\n"
            "                opt.zero_grad()\n"
            "                pred = model(xb)\n"
            "                loss = loss_fn(pred, yb)\n"
            "                loss.backward()\n"
            "                opt.step()\n"
            "        model.eval()\n"
            "        with torch.no_grad():\n"
            "            pred_scaled = model(torch.tensor(X_dl_test, dtype=torch.float32).unsqueeze(-1)).numpy()\n"
            "        pred = scaler_dl.inverse_transform(pred_scaled.reshape(-1, 1)).ravel()\n"
            "        y_true = scaler_dl.inverse_transform(y_dl_test.reshape(-1, 1)).ravel()\n"
            "        return y_true, pred\n\n"
            "    dl_specs = [\n"
            "        (LSTMReg, 'LSTM', {}),\n"
            "        (GRUReg, 'GRU', {}),\n"
            "        (SimpleTransformerReg, 'Transformer', {'seq_len': seq_len}),\n"
            "    ]\n"
            "    for cls, label, kw in dl_specs:\n"
            "        y_true_dl, pred_dl = train_torch_model(cls, label, epochs=12, **kw)\n"
            "        evaluate_forecast(label, y_true_dl, pred_dl, results)\n"
            "        dl_predictions[label] = (test_dates_dl, y_true_dl, pred_dl)\n"
            "        print(f'{label} trained.')\n"
            "else:\n"
            "    print('Deep learning skipped (RUN_DEEP_LEARNING=False or PyTorch missing).')"
        ),
        md("## Section 11 — Model Comparison Table"),
        code(
            "comparison = pd.DataFrame(results).sort_values('RMSE').reset_index(drop=True)\n"
            "display(comparison.round(3))\n"
            "comparison.to_csv(DATA_DIR / 'week4_forecast_model_comparison.csv', index=False)\n"
            "print('Saved comparison table to', DATA_DIR / 'week4_forecast_model_comparison.csv')"
        ),
        md(
            "### Interpretation prompts\n"
            "- Which model had the lowest RMSE?\n"
            "- Did complex models beat seasonal naive?\n"
            "- Which model is most interpretable? Most practical for deployment?"
        ),
        md(
            "### Common mistakes / warnings\n"
            "- Random train/test split on time series\n"
            "- Fitting scalers on train+test together\n"
            "- Comparing models on different test lengths without noticing\n"
            "- Over-interpreting small test-set improvements"
        ),
        md(
            "## Section 12 — Student Exercise\n\n"
            "1. Use a chronological train/test split.\n"
            "2. Implement at least one baseline.\n"
            "3. Fit at least one statistical model.\n"
            "4. Fit at least one ML model.\n"
            "5. Compare MAE / RMSE / MAPE.\n"
            "6. Choose a model and justify interpretability, stability, and practicality.\n\n"
            "### Reflection questions\n"
            "- When would you prefer SARIMA over XGBoost?\n"
            "- What happens if trend changes after the training period?\n"
            "- Why is seasonal naive strong on AirPassengers?"
        ),
        md(
            "## Mini summary\n"
            "- Respect time order in splits and feature engineering.\n"
            "- Always benchmark against naive baselines.\n"
            "- Classical models capture autocorrelation structure; ML needs explicit features.\n"
            "- Deep learning is optional and data-hungry."
        ),
        md(
            "## Final task checklist\n"
            "- [ ] Time-based split plotted\n"
            "- [ ] At least 3 baselines / statistical / ML models compared\n"
            "- [ ] Metrics table saved\n"
            "- [ ] Model choice explained\n"
            "- [ ] Limitations noted"
        ),
        code("print('Week 4 Day 2 Time Series Forecasting completed successfully.')"),
    ]
